name: main
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
      - name: print
        if: ./main == "Hello World"
        run: echo "PASS"
